# Generated by Django 4.1.7 on 2023-04-12 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meet', '0002_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(related_name='group_participants', to=settings.AUTH_USER_MODEL, verbose_name='member'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('dateAdded', models.DateTimeField(auto_now_add=True, verbose_name='create')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_host', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(related_name='event_participants', to=settings.AUTH_USER_MODEL, verbose_name='member')),
                ('tag', models.ManyToManyField(to='meet.tag', verbose_name='Tag')),
            ],
        ),
    ]
