# Generated by Django 4.1.7 on 2023-04-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_event_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tag',
        ),
    ]
