# Generated by Django 4.1.7 on 2023-04-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0005_remove_event_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='tag',
            field=models.ManyToManyField(blank=True, to='meet.tag', verbose_name='Tag'),
        ),
    ]
