# Generated by Django 4.1.7 on 2023-04-14 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_alter_group_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 4, 42, 16, 817532, tzinfo=datetime.timezone.utc), verbose_name='Date'),
            preserve_default=False,
        ),
    ]
