# Generated by Django 4.1.7 on 2023-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0009_remove_event_date_event_held_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default=1, max_length=30, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
